test_script:
- sh: |
    declare JDK_VERSIONS=( "7" "8" "9" "10" )
    declare -A VERSIONS
    VERSIONS["7"]="1.7.0"
    VERSIONS["8"]="1.8.0"
    VERSIONS["9"]="9-internal"
    VERSIONS["10"]="(javac|build) 10"
    for v in "${JDK_VERSIONS[@]}"; do
        JVAR=JAVA_HOME_${v}_X64
        export JAVA_HOME=${!JVAR}
        export PATH=$JAVA_HOME/bin:$PATH
        java -version
        javac -version
        if [[ $(java -version 2>&1) =~ ${VERSIONS[$v]} ]] && [[ $(javac -version 2>&1) =~ ${VERSIONS[$v]} ]]; then
            echo "Version is Correct"
        else
            echo "[ERROR] Version of JDK is incorrect!" 1>&2;
            exit 2;
        fi
    done

build: off
